### ISSUE TITLE
Chat index bug

### ISSUE THREAD

**Issue by FinalDoom** [FinalDoom/FFXI-FishingForm#25]
**[Original report](https://bitbucket.org/FinalDoom/ffxi-fishingform/issue/25) by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

```
#!c#
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FFACETools.FFACE.ChatTools.CleanTimeStamp(String s)
   at FFACETools.FFACE.ChatTools.CleanLine(String line, LineSettings lineSettings)
   at FFACETools.FFACE.ChatTools.GetNextLine(LineSettings lineSettings)
   at Fishing.FishChat.NewChat()
   at Fishing.FishingForm.timer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

Worth investigating further, but not my code.
