### ISSUE TITLE
Reattach bug on logout

### ISSUE THREAD

**Issue by FinalDoom** [FinalDoom/FFXI-FishingForm#28]
**[Original report](https://bitbucket.org/FinalDoom/ffxi-fishingform/issue/28) by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

Part of trying to fix the clock. Possibly invalid.
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Fishing.FishingForm.Reattach()
   at Fishing.FishingForm.timer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

[fix] Should fix #23, clock continues on logout/shutdown. Also fixes #28.
