### ISSUE TITLE
v1.7.0.19 issues

### ISSUE THREAD

**Issue by FinalDoom** [FinalDoom/FFXI-FishingForm#75]
**[Original report](https://bitbucket.org/FinalDoom/ffxi-fishingform/issue/75) by Anonymous.**

----------------------------------------

The new itemizer option crashes from a fresh install. Once inventory is full it crashes whether I have both sack and satchel selected, just one, or neither. Tried with new FFACE and same issue.

When I was trying to verify if new fish were uploading properly it gave me this error and an empty xml file:

ERROR: Error downloading new fish for Ebisu Fishing Rod
System.NullReferenceException: Object reference not set to an instance of an object.
   at Fishing.FishDB.AddNewFish(String& fish, String zone, String bait, String rod, String ID1, String ID2, String ID3, Boolean wanted, Boolean fromDB)
   at Fishing.FishSQL.DoDownloadFish()

Great work otherwise..thanks!

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

Fixed the issue with the DB. stupid typo.

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

Getting bait part of itemizer stuff works. Will have to find a place to test the inventory part.

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

[fix] fixes #75, db updated
