### ISSUE TITLE
Stops fishing

### ISSUE THREAD

**Issue by FinalDoom** [FinalDoom/FFXI-FishingForm#92]
**[Original report](https://bitbucket.org/FinalDoom/ffxi-fishingform/issue/92) by Anonymous.**

----------------------------------------

Hello!

First and foremost, thank you for your time and help to continuously update the program!

I've given this update a try and ran as administrator as per usual. I caught a Hakuryu and updated the list. However, at random it will begin casting and then suddenly the Stop reverts back to Start and the button and status line turn red.

http://i.imgur.com/FsoyE2j.jpg

I'm using Windower and Windows 7 x64 Ultimate with .net etc if that helps any. 

Thanks for your time and help!

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

These issues are really really difficult to solve, because they usually only happen for one or two people, and it's usually something stupid like lag timing (stupid game/logic, not you).

Hoping you're listening to this page, does the old version still work? I don't foresee any functionality updates in the near future that would make upgrading worthwhile if the old one works and the new one doesn't.

In the mean time, I may work on an option to enable extra debug output or something, to make these things easier to track. I should merge in some of RZN (I think)'s code, like log saving and whatnot, too.

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

Need more information--debug functionality, log exporting.

**Comment by FinalDoom** [comment]
**Original comment by Nathan A (Bitbucket: [Nathan A](https://bitbucket.org/{6308f37d-d802-4065-9ace-52c2c4cf4542}), GitHub: [ennoia](https://github.com/ennoia)).**

----------------------------------------

Apologies for the delay 

The old versions do not work for me unfortunately. They end up being detected as a false positive by Norton, and when I exempt them and go to run it they end up freezing sadly.

That's the peculiar thing about it and I know I didn't mention this is that there's nothing in the db log portion of the program when this happens. The start/stop button and status line are the only two things that highlight red indicating some type of problem. When the button turns red and reverts to "stop" the fish is hooked. If I press start it will release or catch depending on the wanted/unwanted etc then recast and repeat itself in this manner.

The only issue I've seen in the db log is this:


```
#!c#

[11:32:28] Checking program version.
[11:32:28] Beginning database sync.
[11:32:28] Uploading 1 fish.
[11:32:28] 1: "Matsya2" renamed to "Matsya". (Ebisu Fishing Rod)
[11:32:28] WARNING: Error renaming fish "Matsya2" to "Matsya"
[11:32:28] MySql.Data.MySqlClient.MySqlException: Duplicate entry '1687-654' for key 'PRIMARY'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Fishing.FishSQL.RenameFish(String fish, String oldName, String rod, String ID1, String ID2, String ID3)
[11:32:28] Downloading 16 rods' data.
[11:32:28] Getting information for Ebisu Fishing Rod (#1).
[11:32:28] Getting information for Lu Shang's F. Rod (#2).
[11:32:28] Getting information for Bamboo Fish. Rod (#3).
[11:32:29] Getting information for Carbon Fish. Rod (#4).
[11:32:29] Getting information for Clothespole (#5).
[11:32:29] Getting information for Comp. Fishing Rod (#6).
[11:32:29] Getting information for Fastwater F. Rod (#7).
[11:32:29] Getting information for Glass Fiber F. Rod (#8).
[11:32:29] Getting information for Halcyon Rod (#9).
[11:32:29] Getting information for Hume Fishing Rod (#10).
[11:32:29] Getting information for Mithran Fish. Rod (#11).
[11:32:29] Getting information for S.H. Fishing Rod (#12).
[11:32:30] Getting information for Tarutaru F. Rod (#13).
[11:32:30] Getting information for Willow Fish. Rod (#14).
[11:32:30] Getting information for Yew Fishing Rod (#15).
[11:32:30] Getting information for MMM Fishing Rod (#16).
[11:32:30] Database sync finished.
```


I am not sure if there's another way to possibly capture what's going on other than the db log but if there is I'll try to help get it

**Comment by FinalDoom** [comment]
**Original comment by FinalDoom (Bitbucket: [FinalDoom](https://bitbucket.org/{d7bd602f-3443-4a67-a621-ea4c07d584c2}), GitHub: [FinalDoom](https://github.com/FinalDoom)).**

----------------------------------------

Nothing at all in the db log? That'd indicate to me that your windows or norton firewall is blocking it from accessing the ec2 database. I'd think it might throw an error in that case, though.

That's a strange looking error trace you've got there. I thought I wrote the rename stuff to not do that. I'll have to take a look at it. I think that it's probably just one of those things that happens, and you needn't worry about it. If it keeps happening, you can find the offending Matsya2 entry in ebisu.xml and name it Matsya, and remove any rename="blah" things from the tag.

I haven't worked on FishingForm for a while, so getting back into it to do the debug logging necessary to make all this work will take a bit of time. I'll post back here when I've got an update out that could help diagnose things.
